---
language: node_js
node_js:
  - "8"
  - "10"
  - "12"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

# branches:
#   only:
#     - master

install:
  - npm install

script:
  - ember build
#   - npm run lint:hbs
#   - npm run lint:js
#   - npm test
