FROM node:20.12.1-slim
WORKDIR /src
ARG NODE_ENV
ARG VITE_GOOGLE_MAPS_API_KEY
COPY . .
ENV NODE_ENV=$NODE_ENV
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
RUN npm install
RUN npm run build
EXPOSE 4200
ENTRYPOINT ["npm", "run", "start"]
