import type { LayerSpecification } from "maplibre-gl";

export const transportation: LayerSpecification[] = [
  {
    id: "tunnel_motorway_casing",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "brunnel"], "tunnel"],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "butt", "line-join": "miter" },
    paint: {
      "line-color": "rgb(213, 213, 213)",
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        5.8,
        0,
        6,
        3,
        20,
        40,
      ],
    },
  },
  {
    id: "tunnel_motorway_inner",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "brunnel"], "tunnel"],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "rgb(234,234,234)",
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        4,
        2,
        6,
        1.3,
        20,
        30,
      ],
    },
  },
  {
    id: "aeroway-taxiway",
    type: "line",
    source: "openmaptiles",
    "source-layer": "aeroway",
    minzoom: 12,
    filter: ["match", ["get", "class"], ["taxiway"], true, false],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "hsl(0,0%,88%)",
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.55],
        ["zoom"],
        13,
        1.8,
        20,
        20,
      ],
    },
  },
  {
    id: "aeroway-runway-casing",
    type: "line",
    source: "openmaptiles",
    "source-layer": "aeroway",
    minzoom: 11,
    filter: ["match", ["get", "class"], ["runway"], true, false],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "hsl(0,0%,88%)",
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        11,
        6,
        17,
        55,
      ],
    },
  },
  {
    id: "aeroway-area",
    type: "fill",
    source: "openmaptiles",
    "source-layer": "aeroway",
    minzoom: 4,
    filter: [
      "all",
      ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false],
      ["match", ["get", "class"], ["runway", "taxiway"], true, false],
    ],
    paint: {
      "fill-color": "rgba(255, 255, 255, 1)",
      "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0, 14, 1],
    },
  },
  {
    id: "aeroway-runway",
    type: "line",
    source: "openmaptiles",
    "source-layer": "aeroway",
    minzoom: 11,
    filter: [
      "all",
      ["match", ["get", "class"], ["runway"], true, false],
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "rgba(255, 255, 255, 1)",
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.5],
        ["zoom"],
        11,
        4,
        17,
        50,
      ],
    },
  },
  {
    id: "road_area_pier",
    type: "fill",
    source: "openmaptiles",
    "source-layer": "transportation",
    filter: [
      "all",
      ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false],
      ["==", ["get", "class"], "pier"],
    ],
    paint: { "fill-antialias": true, "fill-color": "rgb(242,243,240)" },
  },
  {
    id: "road_pier",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["match", ["get", "class"], ["pier"], true, false],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "rgb(242,243,240)",
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        15,
        1,
        17,
        4,
      ],
    },
  },
  {
    id: "highway_path",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["==", ["get", "class"], "path"],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "rgb(234, 234, 234)",
      "line-opacity": 0.9,
      "line-width": [
        "interpolate",
        ["exponential", 1.2],
        ["zoom"],
        13,
        1,
        20,
        10,
      ],
    },
  },
  {
    id: "highway_minor",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 8,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["match", ["get", "class"], ["minor", "service", "track"], true, false],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "hsl(0,0%,88%)",
      "line-opacity": 0.9,
      "line-width": [
        "interpolate",
        ["exponential", 1.55],
        ["zoom"],
        13,
        1.8,
        20,
        20,
      ],
    },
  },
  {
    id: "highway_major_casing",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 11,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
    ],
    layout: { "line-cap": "butt", "line-join": "miter" },
    paint: {
      "line-color": "rgb(213, 213, 213)",
      "line-dasharray": [12, 0],
      "line-width": [
        "interpolate",
        ["exponential", 1.3],
        ["zoom"],
        10,
        3,
        20,
        23,
      ],
    },
  },
  {
    id: "highway_major_inner",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 11,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "#fff",
      "line-width": [
        "interpolate",
        ["exponential", 1.3],
        ["zoom"],
        10,
        2,
        20,
        20,
      ],
    },
  },
  {
    id: "highway_major_subtle",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    maxzoom: 11,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: { "line-color": "hsla(0,0%,85%,0.69)", "line-width": 2 },
  },
  {
    id: "highway_motorway_casing",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "butt", "line-join": "miter" },
    paint: {
      "line-color": "rgb(213, 213, 213)",
      "line-dasharray": [2, 0],
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        5.8,
        0,
        6,
        3,
        20,
        40,
      ],
    },
  },
  {
    id: "highway_motorway_inner",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        5.8,
        "hsla(0,0%,85%,0.53)",
        6,
        "#fff",
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        4,
        2,
        6,
        1.3,
        20,
        30,
      ],
    },
  },
  {
    id: "highway_motorway_subtle",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    maxzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["==", ["get", "class"], "motorway"],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": "hsla(0,0%,85%,0.53)",
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        4,
        2,
        6,
        1.3,
      ],
    },
  },
  {
    id: "railway_transit",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 16,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "class"], "transit"],
        ["match", ["get", "brunnel"], ["tunnel"], false, true],
      ],
    ],
    layout: { "line-join": "round" },
    paint: { "line-color": "#dddddd", "line-width": 3 },
  },
  {
    id: "railway_transit_dashline",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 16,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "class"], "transit"],
        ["match", ["get", "brunnel"], ["tunnel"], false, true],
      ],
    ],
    layout: { "line-join": "round" },
    paint: {
      "line-color": "#fafafa",
      "line-dasharray": [3, 3],
      "line-width": 2,
    },
  },
  {
    id: "railway_service",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 16,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["all", ["==", ["get", "class"], "rail"], ["has", "service"]],
    ],
    layout: { "line-join": "round" },
    paint: { "line-color": "#dddddd", "line-width": 3 },
  },
  {
    id: "railway_service_dashline",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 16,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["==", ["get", "class"], "rail"],
      ["has", "service"],
    ],
    layout: { "line-join": "round" },
    paint: {
      "line-color": "#fafafa",
      "line-dasharray": [3, 3],
      "line-width": 2,
    },
  },
  {
    id: "railway",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 13,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["all", ["!", ["has", "service"]], ["==", ["get", "class"], "rail"]],
    ],
    layout: { "line-join": "round" },
    paint: {
      "line-color": "#dddddd",
      "line-width": [
        "interpolate",
        ["exponential", 1.3],
        ["zoom"],
        16,
        3,
        20,
        7,
      ],
    },
  },
  {
    id: "railway_dashline",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 13,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      ["all", ["!", ["has", "service"]], ["==", ["get", "class"], "rail"]],
    ],
    layout: { "line-join": "round" },
    paint: {
      "line-color": "#fafafa",
      "line-dasharray": [3, 3],
      "line-width": [
        "interpolate",
        ["exponential", 1.3],
        ["zoom"],
        16,
        2,
        20,
        6,
      ],
    },
  },
  {
    id: "highway_motorway_bridge_casing",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "brunnel"], "bridge"],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "butt", "line-join": "miter" },
    paint: {
      "line-color": "rgb(213, 213, 213)",
      "line-dasharray": [2, 0],
      "line-opacity": 1,
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        5.8,
        0,
        6,
        5,
        20,
        45,
      ],
    },
  },
  {
    id: "highway_motorway_bridge_inner",
    type: "line",
    source: "openmaptiles",
    "source-layer": "transportation",
    minzoom: 6,
    filter: [
      "all",
      [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      [
        "all",
        ["==", ["get", "brunnel"], "bridge"],
        ["==", ["get", "class"], "motorway"],
      ],
    ],
    layout: { "line-cap": "round", "line-join": "round" },
    paint: {
      "line-color": [
        "interpolate",
        ["linear"],
        ["zoom"],
        5.8,
        "hsla(0,0%,85%,0.53)",
        6,
        "#fff",
      ],
      "line-width": [
        "interpolate",
        ["exponential", 1.4],
        ["zoom"],
        4,
        2,
        6,
        1.3,
        20,
        30,
      ],
    },
  },
];
